language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: DuwUsqmC4A9U52RXCYs5M8p7HVQKkEI328o6it4NG+fjg0n0E+edJ5azqFmiArWBQ/4N8ZoNqUz+H896Pojt8PFCmBUPGTjxuUX8XsaP72PDEV7QJ7drGd9mZ1tOlb8XxjLPH4KuSTMqZjwTA936zELdS820I/8GX6QCSalWwK8=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: fYjjTqv74fRmicpOTDMtoY0AhKrEhufnZW4hgTVk/F9b8LJrce5oYJIPVWMDzokbWf4RnkNVo7eAMiGs5oAxGw5efwi44SBje0pYpcKeeKDSDh2q6CXT2QCo1cDzmTAm8aBpYsh/XBz0s5jqnJtK+eZccM4qBgqGtlV0P6iOtl8=
sudo: false
